//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foosure.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessObjectsContainer : DbContext
    {
        public BusinessObjectsContainer()
            : base("name=BusinessObjectsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<GameNode> GameNodes { get; set; }
        public DbSet<GameNodeType> GameNodeTypes { get; set; }
        public DbSet<GameNodeToGameNodeTypeMap> GameNodeToGameNodeTypeMaps { get; set; }
        public DbSet<UserToTeamMap> UserToTeamMaps { get; set; }
        public DbSet<SeasonToGameNodeMap> SeasonToGameNodeMap { get; set; }
        public DbSet<TeamToGameNodeMap> TeamToGameNodeMaps { get; set; }
    }
}
