//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foosure.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamToGameNodeMap
    {
        public int TeamId { get; set; }
        public int GameNodeId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual GameNode GameNode { get; set; }
    }
}
